### ISSUE TITLE
Отображение WiFi точек на карте

### ISSUE THREAD

**Issue by akokarev** [binarymaster/3WiFi#1]
Необходимо реализовать отображение всех найденных WiFi точек (порядка 40 тыс.) на карте.

Рассматриваю вариант с RemoteObjectManager (https://tech.yandex.ru/maps/doc/jsapi/2.1/dg/concepts/remote-object-manager/about-docpage/)

На текущий момент реализовано через objectManager работает нормально примерно с 1000 точками.
Скрипт map.php отображает Яндекс карту и грузит данные из файла data.json.
Файл data.json предварительно формируется скриптом makemap.php на основании данных в БД.
Скрипты chkxy.php и rechkxy.php заполняют поля БД координатами на основании BSSID через API геолокации Яндекса

**Comment by akokarev** [comment]
Сделал карту с использованием LoadingObjectManager http://3wifi.tk/map2.php, но те же грабли вид сбоку.. Карта открывается, подгружаются точки по мере необходимости для просматриваемого района. Работает кластеризация.
Но есть 2 бага:
1) При достижении суммарно около 1-3 тыс точек больше точек не отображается.
2) Если на вновь подгружаемом участке нет точки, то в менеджер возвращается пустой результат, после чего менеджер перестает отображать подгружаемые данные.

Дальше развивать это решение не имеет смысла, т.к. большой объем данных намертво вешает LoadingObjectManager

**Comment by akokarev** [comment]
Переделал LoadingObjectManager в RemoteObjectManager http://3wifi.tk/map3.php, осталось реализовать серверную кластеризацию

**Comment by akokarev** [comment]
Есть один простой способ кластеризации - поделить отображаемую область на одинаковые области (пополам, на четыре, на восемь и т.д.) и посчитать кол-во точек для каждой области. Если точка одна (две, три, некоторое малое число) - вывести точку, если точек много - вывести кластер посередине области. 
Но у такой кластеризации куча минусов - не красиво, не оптимально выбираемые кластеры

**Comment by binarymaster** [comment]
Кластеры надо выбирать в зависимости от текущего масштаба карты, а также возможно её разрешения в пикселях.

**Comment by akokarev** [comment]
Масштаб интересен 3х видов:
1) максимальное приближение - кластеризация не нужна, либо отображать балун с информацией
2) максимальное удаление - можно кластеризовать по регионам (Америка С\Ю, Европа, Азия и т.д.)
3) во всех остальных случаях кластеризовать динамически, как я описывал.

На входе скрипт получает координаты противоположных углов карты, для которых нужно получить данные. По-этому сама карта мало интересует, делаем выборку из БД по этим координатам и все.

**Comment by akokarev** [comment]
Исправил недочеты в getmap.php. 
На данный момент отлично отображает сразу все точки на карте, однако кластеризация не используется.

**Comment by binarymaster** [comment]
Оказалось, нужен был уникальный id для каждой точки на карте. Супер! :)

**Comment by binarymaster** [comment]
Серверная кластеризация маркеров на карте. От теории к практике
http://habrahabr.ru/post/268621/

На античате подкинули ссылку, думаю, это есть решение проблемы.

**Comment by akokarev** [comment]
Сделал простую кластеризацию, но есть еще над чем работать

**Comment by akokarev** [comment]
Интересный модуль для отображения тепловых карт яндекс https://github.com/yandex/mapsapi-heatmap

**Comment by LennyLip** [comment]
@akokarev пытаюсь сделать RemoteObjectManager как у вас. Что-то пока не выходит. Не подскажите tileNumber от яндекса приходит, эти номера совместимы с координатами тайлов которы мы генерим из географических координат? ( https://github.com/binarymaster/3WiFi/blob/c3fdf83a797bd527a25c5c389f999fb1d61be824/quadkey.php#L52 )

Подскажите пожалуйста, весь инет перерыл, что-то не могу найти. (по сути вопрос сводится, к тому, у yandex также разделен мир на 0.1.2.3 и т.д.?)

И еще вопрос вдогонку. не могли бы вы скинуть номер quad key для каких-нибудь lat lon zoom=23, что-то у меня quadkey везде разный получается,

Извините за вопросы не по теме, потом удалим тогда.

**Comment by binarymaster** [comment]
С кластеризацией вроде уже проделали всё что можно, и всё более-менее работает.
