### ISSUE TITLE
Шаблонизатор

### ISSUE THREAD

**Issue by LennyLip** [binarymaster/3WiFi#20]
попытался развернуть сайт. 

получил 
![shabl](https://cloud.githubusercontent.com/assets/955994/13497321/c9d4c4f0-e165-11e5-9186-c160ee444668.png)

походу используется какой-то шаблонизатор? но в мануале не указано, да в php я не силен.  Что надо доставить, подскажите?

**Comment by binarymaster** [comment]
Самописный шаблонизатор, да.

Что-то мне подсказывает, что у вас проблема в .htaccess - mod_rewrite в наличии?

**Comment by LennyLip** [comment]
```
#apache2ctl - M | grep "rewrite_module"
 rewrite_module
Syntax OK
```

**Comment by binarymaster** [comment]
Значит в `index.php` что-то пошло не так, копайте в этом направлении -  он отвечает за вывод страниц.

**Comment by LennyLip** [comment]
тьфу блин, в дебиане в apache по умолчанию "DirectoryIndex index.html". Так что он грузился, вместо index.php. Добавил "DirectoryIndex index.php index.html", все ок.

ps. небольшой офтоп, я  все по своей теме кластеризации, не могли бы вы скинуть небольшой файлик (маленький любой)  лога routerscan куда-нибудь. Хотелось бы чисто кластеризацию поизучать, а тут еще сканировать надо, а я в деревне - тут нечего сканировать :D будьте так любезны.

**Comment by binarymaster** [comment]
Можете попросить образцы отчётов в теме на форуме (ссылка есть на сайте 3WiFi), я в ближайшее время предоставить не смогу.

**Comment by LennyLip** [comment]
Хотя в апаче прописан index.php , только после index.html. Лучше бы index.html переименовать. Все равно какая-то проблема - в /map и /upload: head и body что-то не заполняются.

Установка стандартная дебиан 7, никакие конфиги не правились

**Comment by LennyLip** [comment]
```
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
```

поменял на 

```
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

пока не помогло, бесконечный редирект пишет. 
убрал DirectoryIndex index.php index.html -> DirectoryIndex index.html index.php , тоже самое.

**Comment by LennyLip** [comment]
Стандартная установка debian 7:

```
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
```

меняем на 

```
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

добавляем

https://github.com/binarymaster/3WiFi/blob/master/.htaccess :

```
Options -Indexes

RewriteEngine on
```

-->

```
Options -Indexes
Options -MultiViews

RewriteEngine on
```

**Comment by LennyLip** [comment]
- зависит от php5-curl

запускать демонов можно так

```
# Upload routine loads data into database
nohup php -f 3wifid.php uploads &
# Finalize routine prepares tasks for finalization
nohup php -f 3wifid.php finalize &
# Geolocate routine locates new added BSSIDs on map
nohup php -f 3wifid.php geolocate  &
```

логи лежат в hohup.out

**Comment by Shagrath82** [comment]
Вот не могу разобраться как запустить демонов на хостинге через Cron. Через SSH они живут от силы сутки, поэтому хотелось бы автоматизировать весь процесс.Был бы благодарен помощи
