### ISSUE TITLE
Ошибка при определении координат

### ISSUE THREAD

**Issue by akokarev** [binarymaster/3WiFi#26]
`[root@3wifi public_html]#php 3wifid.php geolocate`

> PHP Notice:  Trying to get property of non-object in /home/admin/web/3wifi.ogurcom.ru/public_html/geoext.php on line 44

`var_dump($data)`

> false

`var_dump($json)`

> NULL

**Comment by akokarev** [comment]
может там поставить
`if (!$data) {break;}`

**Comment by binarymaster** [comment]
Попробуй вот так:
```php
	do
	{
		$data = cURL_Get("... url ...");
		if (!$data)
		{
			$tries--;
			sleep(2);
		}
	} while (!$data && $tries > 0);
```
Если заработает, напиши, коммитну.

**Comment by binarymaster** [comment]
Да, можно просто там остановить через break или return.

**Comment by binarymaster** [comment]
Кстати... исходя из этой ошибки, у тебя на хостинге нет доступа к AlterGeo.

Рекомендую протестировать, работает ли геолокация и HTTP запросы на другие серверы.

**Comment by akokarev** [comment]
Эта ошибка вываливается не постоянно, бавает 3-5 точек определяет

**Comment by akokarev** [comment]
Теперь в строке 135 таже ошибка вылетает.
В $data вываливается html страница, дескать не введена капча.
Ну а в $json значение NULL

Текст страницы из $data:

> Please enable cookies.
> One more step
> Please complete the security check to access api.mylnikov.org
> Why do I have to complete a CAPTCHA?
> Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
> What can I do to prevent this in the future?
> If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
> If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.

Может прикрутить сервис распознования капчи?

**Comment by akokarev** [comment]
Или как вариант скачать его базу к себе
https://www.mylnikov.org/download

**Comment by binarymaster** [comment]
А если один раз ввести капчу вручную, и запомнить cookies, сколько оно потом работает?

**Comment by akokarev** [comment]
Не знаю, да и смысл? Есть же его база офлайн.. Там все что нам нужно и дальше больше. Правда весит она в csv формате под 3Гб..
Сейчас пробую её загрузить в базу.
Можно пробивать по этой базе, а если не нашлось, тогда уже искать через его api

**Comment by levin-kelevra** [comment]
`php 3wifid.php geolocate
3WiFi Daemon Script

[15:07:14] MySQL database connected.
[15:07:14] Running 'geolocate' task...
PHP Fatal error:  Cannot redeclare gzdecode() in /usr/share/nginx/html/3WiFi/geoext.php on line 13
`

Кажется сюда же...
коммит f771963f945333d0d04589dd1cd89585dbaa73cf

И ещё вопрос: как использовать wifi.csv из ссылки выше? )

**Comment by mylnikovorg** [comment]
Здравствуйте! 
Дело все в том, что для использования API согласно https://www.mylnikov.org/archives/1170 необходимо использовать ключ "data=open". При таком использовании капча появляться не будет
