### ISSUE TITLE
Реализовать API для получения названия устройства по MAC

### ISSUE THREAD

**Issue by binarymaster** [binarymaster/3WiFi#43]
Сама функция уже реализована, надо только добавить возможность вызывать её через API, например `apidev`.

**Comment by AnonimDev** [comment]
Посмотрел как реализовано API вообще. Насколько я понимаю мы заходим в папку 

> ../api

 а оттуда перенаправление на 

> 3wifi.php

А там уже swich и разбираем по ключам что пришло. Есть там case, который нужен. Позже посмотрю что можно сделать.

**Comment by binarymaster** [comment]
Да, всё именно так. Спасибо!

**Comment by binarymaster** [comment]
@AnonimDev за 4 года не дождался, пришлось реализовать самому.
