### ISSUE TITLE
Авторизация\регистрация пользователей

### ISSUE THREAD

**Issue by akokarev** [binarymaster/3WiFi#5]
Необходимо реализовать:
1. Регистрацию пользователей с подтверждением по e-mail;
2. Авторизацию на сайте по логину\паролю;
3. Поиск для авторизованных пользователей без кодового слова, и отображение карты с паролями, а для неавторизованных - с запросом кодового слова и без отображения паролей на карте.
4. Ввести учет загруженных данных по пользователям; сделать в меню пользователя отображение загруженных им данных (таблица и карта, список комментариев и возможность редактировать комментарии), статистику (по аналогии с общей)

**Comment by akokarev** [comment]
Пароли предлагаю хранить в виде MD5 хэша 
вида MD5( MD5("password_salt1") + "_salt2_salt3") ), где
password - введенный пароль (не менее 6 символов)
salt1 - первая общая соль для всей базы, общедоступна на гитхабе, храниться в конфиге
salt2 - вторая общая соль для всей базы, сообщается только проектам участникам синхронизации, храниться в конфиге
salt3 - случайная соль, генерируется при регистрации пользователя, храниться в БД
Размеры соли надо брать не менее 10 символов каждая, состоят из латинских букв, цифр и спецсимволов.
1. Пользователь отправляет запрос на авторизацию
2. Сервер отправляет форму со скрытым полем salt1
3. Пользователь заполняет поля login и password, скрипт считает hash1=MD5("password_salt1") и отправляет серверу пару login:hash1
4. Сервер находит в БД пользователя, поля salt3, hash и status пользователя, высчитывает hash2=MD5(hash1+"_salt2_salt3"). Если пользователь существует, hash2=hash, status="active", то авторизацию считать успешной. Иначе сообщить "Не верный логин\пароль или пользователь не активен"

Таким образом пароль пользователя будет надежно защищен при передаче между сервером и клиентом, от перебора в случае утечки БД. А так же легко реализовать синхронизацию между разными БД без разглашения пароля. Фактически сервер никогда не получает пароль в открытом виде.

**Comment by akokarev** [comment]
Частично выполнено https://github.com/binarymaster/3WiFi/commit/576227438690e9df0efb964a17f2b500f8032887

**Comment by binarymaster** [comment]
Единственная недоделанная часть:

> Регистрацию пользователей с подтверждением по e-mail;

Но вряд ли будем её доделывать, т.к. был выбран путь кодов приглашений.
