### ISSUE TITLE
Адаптировать карту под мобильные устройства

### ISSUE THREAD

**Issue by ghost** [binarymaster/3WiFi#62]
С телефона очень неудобно работать с картой, прошу адаптировать сервис под мобильные устройства. На первое время можно просто уменьшать фрейм с картой в ~2-3 раза. Переключение производить при распознавании мобильного устройства, либо добавить кнопку "мобильная версия" в уголок футера

**Comment by binarymaster** [comment]
3WiFi уже умеет распознавать мобильные устройства: https://github.com/binarymaster/3WiFi/blob/e971918fce7b4a9e0e35bb0a9afe3ae0265a574a/index.html#L12

Если у вас есть конкретные мысли (в виде кода), как улучшить мобильную версию сайта, присылайте пулл реквест.
