### ISSUE TITLE
not working with xampp

### ISSUE THREAD

**Issue by zedorgan** [binarymaster/3WiFi#63]
i installed 3wifi on xampp on windows but i got many errors and warnings:

Notice: Undefined index: uselocation in C:\xampp\htdocs\3wifi\index.php on line 148
Notice: Undefined index: lat in C:\xampp\htdocs\3wifi\index.php on line 150
Notice: Undefined index: lon in C:\xampp\htdocs\3wifi\index.php on line 151
Notice: Undefined index: rad in C:\xampp\htdocs\3wifi\index.php on line 152
Notice: Undefined index: lat in C:\xampp\htdocs\3wifi\index.php on line 154
Notice: Undefined index: lon in C:\xampp\htdocs\3wifi\index.php on line 155
Notice: Undefined index: rad in C:\xampp\htdocs\3wifi\index.php on line 156
Notice: Undefined index: theme in C:\xampp\htdocs\3wifi\index.php on line 183
Notice: Undefined variable: l10n in C:\xampp\htdocs\3wifi\index.php on line 210
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\3wifi\index.php on line 90

what should i do to fix it please

**Comment by binarymaster** [comment]
No idea. Ask in 3WiFi or Router Scan Telegram chat.
