### ISSUE TITLE
Зависло определение координат

### ISSUE THREAD

**Issue by levin-kelevra** [binarymaster/3WiFi#9]
Импортнул csv на 2000 точек, смотрю в статистику и вижу, что в поле "В процессе обработки" постоянно написано 1000.
Как протолкнуть?
В логах ошибок нет.

**Comment by binarymaster** [comment]
Это специфика загрузчика... в процессе исправления

**Comment by akokarev** [comment]
Тоже интересовался этим вопросом, вот что выяснил.
При загрузке upload.php загружает данные в базу, широта и долгота ставятся по-умолчанию в none. Дальше в upload.php делает flush(), т.е. результаты загрузки передаются в браузер и дальше запускает определение координат среди точек где широта и долгота none.
В тоже время статистика по json запрашивает данные у 3wifi.php, а в нем уже смотрим строчки:
if ($res = $db->query("SELECT COUNT(*) FROM `free` WHERE `BSSID` LIKE '**:**:**:**:**:**' AND `latitude` = 'none' AND `longitude` = 'none'"))
    {
        $row = $res->fetch_row();
        $json['stat']['processing'] = (int)$row[0];
        $res->close();
    }
Т.е. это не кол-во точек недогруженных в базу, а кол-во точек, которые в процессе определения координат!
Сам процесс определения координат требует времени, чем больше добавил, тем больше времени необходимо... Ну а у php есть ограничения на время выполнения скриптов, например у меня это было 60 сек на платном хостинге. В итоге, если загрузить сразу много точек, то часть из них успевает пройти проверку координат, часть нет - upload.php останавливается по времени. Ну и как результат видим зависшие "в процессе".
Как протолкнуть? Ну как вариант - загрузить в базу ещё один маленький файл отчёта, одной точки хватит. Таким образом породишь ещё один процесс upload.php. Но делать так надо с осторожностью, можно повесить сервак наглухо или добиться бана со стороны геолокационных сервисов. Можно увеличить время исполнения скриптов, что тоже ни есть гуд. А можно сделать отдельный шеддуллер по инициализации геопроверок и поставить в нем лимит на кол-во проверяемых за раз точек. Думаю вот это и будет реализовано в будущем.

**Comment by levin-kelevra** [comment]
Я за шедулер, т.к. это более корректный вариант.
С теми точками я уже разобрался, как раз подсунул еще один файлик.

**Comment by binarymaster** [comment]
Исправил это тут: https://github.com/binarymaster/3WiFi/commit/e441aac1c16876651dd7f95850f7421a8efd926f
(установил бесконечное время выполнение, и отключил реакцию на отмену запроса)

Если всё-таки что-то осталось необработанным, то можно отправить запрос `/3wifi.php?a=check`
